### ISSUE TITLE
Add "wiring" graphics for most common setups

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#14]
one probably could add the graphics of rcgroups post https://www.rcgroups.com/forums/showpost.php?p=48821735&postcount=332 to proper places in the docs (they are linked to in the mLRS main README page, but this is maybe not prominent enough to be useful)

the pics need some update too as some info has slightly changed

triggerd by discussion https://www.rcgroups.com/forums/showpost.php?p=50757843&postcount=1555, https://www.rcgroups.com/forums/showpost.php?p=50758181&postcount=1556

**Comment by jlpoltrack** [comment]
As opposed to these graphics, what do you think about a table showing the connections that need to be made for all the hardware on both the Tx and Rx side?  I found these block diagrams a bit too high level :)

Example:

![image](https://user-images.githubusercontent.com/41841496/228668786-6f71c9db-163e-4af6-ac4b-4962f63406db.png)

**Comment by olliw42** [comment]
I frankly have no opinion here. To me it always appears like this one user prefers this and this other user prefers that. From pure statistics it seems to me that wire diagrams are more frequently found (JB even draws them in realtime in his live streams when he wants to show a wiring). That's all I can say LOL.

**Comment by jlpoltrack** [comment]
Added an example wiring diagram for the E5 Mini as Tx in this branch: https://github.com/olliw42/mLRS-docu/tree/Seeed-E5-Wiring.

I think it makes sense to try and complete these for each hardware page.  Can worry about the DIY hardware later :)

**Comment by olliw42** [comment]
N I C E !!

shouldn't one maybe also add the green led?

for a short moment I was confused about the top grey line as it seemed to have no label, until I realized that's serial rx,tx. Maybe just some centering, or indeed writing serial Rx, serial Tx, could help

since there is space, one could consider also adding a S-diode suggestion like e.g. BAT42

but I'm really nit-picking now, it's a great and very helpfull drawing

**Comment by olliw42** [comment]
I think the intended graphics are now in the respective setup descriptions.

It probably could be useful - at some point in time - to have a high-level intro-like page with brief descriptions on the various possibilities possible with mLRS. But I think for now this here can be closed.

Pl do not hesitate to reopen if deemed appropriate. :)
