### ISSUE TITLE
esp iflight900 TD appears to be "unstable"

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#176]
there are two reports of issues with the iflight 900 td elrs receiver
- https://github.com/olliw42/mLRS/pull/197#issue-2355444077 and ff
- https://discord.com/channels/1005096100572700794/1005096101239603232/1253284902061867091 and ff

**Comment by jlpoltrack** [comment]
Am thinking that this should be a statement in the Notes sections on the ELRS receivers page - are you thinking of something else?

**Comment by jlpoltrack** [comment]
iFlight hardware no longer supported, so closing.
