### ISSUE TITLE
WioE5 modules, green led wiring

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#19]
@jlpoltrack 
sorry for not having noted this before
for the WioE5 mini dev modules, for which you gratefully have done wiring diagrams, the green led is wired to the gnd post on the usb plug. But this can be done much nicier by using the scl pin as intermediate post, i.e., to wire sda - |>| - SCL and SCL - R - GND. IMHO this is really a nice trick of you. 
or is there a reason you decided now against it?

**Comment by jlpoltrack** [comment]
Never actually used the second LED on E5 Mini - please see PR with updated images.

**Comment by olliw42** [comment]
THX!
