### ISSUE TITLE
Instructions for custom targets, own-made DIY boards

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#22]
it appears that many users build their own boards, which may be derived from but may not be identical to some existing schemes. It probably could be good to have some instructions for how to create a target and compile custom firmware.

**Comment by jlpoltrack** [comment]
Are you thinking that this would primarily focus on updating an existing HAL for a different board layout?  If so, I could details the steps that I took to get my E22 / G4 1W modules working.

**Comment by olliw42** [comment]
well, I'm not totally sure what kind of thing I would have in mind
I just note that quite a signifciant number of mLRS users have made thier own builds, with smaller or larger deviations from the reference builds, and need to adapt&modify the hal

I guess the "correct" approach would be to create a new target, but that's a bit of a tedious step. Currently it seems to me they take an existing target, and just modify the hal. This however likely is not very convennien, e.g. when the firmware is upgraded. I guess my proposal would be to create a new hal file by taking a copy of a "close" one, and in hal.h outcomment the old #inlcude and insert the new file. 

I guess what I did not have in mind is describing which flag and which function etc. needs to be changend in which way. That's really quite tedious. 

However, at the end of the day, I really have no clear idea here. I just note the situation. I guess everything which may help anyone eill be ... well ... helpfull LOL

**Comment by olliw42** [comment]
many thx
