### ISSUE TITLE
Add flashing options/instructions to the WioE5mini & EByte E77 MBL boards

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#24]
motivated by this discussion https://discord.com/channels/1005096100572700794/1005268982691004528/1097733180154445844

**Comment by olliw42** [comment]
thankfully done for WioE5, PR https://github.com/olliw42/mLRS-docu/pull/25 :)

**Comment by jlpoltrack** [comment]
@olliw42 
Do you recall if E77 MBL had readout-protection enabled?  I don't have that hardware but can't see why it would.

**Comment by olliw42** [comment]
unfortunately I can't
maybe the doc can be written to suggest to check if its AA and if not to take action

**Comment by jlpoltrack** [comment]
Done for E77: https://github.com/olliw42/mLRS-docu/pull/33

**Comment by olliw42** [comment]
THANK YOU SO MUCH !!!
