### ISSUE TITLE
SEEEDSTUDIO_WIO_E5.md updates

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#31]
@jlpoltrack 

I just made a change to the SEEEDSTUDIO_WIO_E5.md page, but unfortunately hit the wrong button and so it became a direct commit and not a PR.

Could you pl have a look and double check, and possibly commit your corrections if any?

sorry, and thx.

**Comment by jlpoltrack** [comment]
Looks good to me.

**Comment by olliw42** [comment]
thx :)
