### ISSUE TITLE
Lua: radios with bw screen

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#39]
lua script providing basic support for radios with bw screen is now available. TODO: adapt lua docu accordingly

**Comment by jlpoltrack** [comment]
PR here: https://github.com/olliw42/mLRS-docu/pull/40

**Comment by jlpoltrack** [comment]
PR merged: https://github.com/olliw42/mLRS-docu/pull/40

**Comment by olliw42** [comment]
cool !! many thx
