### ISSUE TITLE
Update pages as half-duplex is now implemented

### ISSUE THREAD

**Issue by jlpoltrack** [olliw42/mLRS-docu#62]
Now that half-duplex is implemented on the Tx side, update pages accordingly.

**Comment by olliw42** [comment]
YO!!

maybe for the WioE5 mini one sould also mention the boot trick you just had suggested to Yibing

**Comment by jlpoltrack** [comment]
> YO!!
> 
> maybe for the WioE5 mini one sould also mention the boot trick you just had suggested to Yibing

PR for E5 here: https://github.com/olliw42/mLRS-docu/pull/63

Could you update your image for E77 to remove diode: 
![image](https://github.com/olliw42/mLRS-docu/assets/41841496/52c2a084-e460-42f8-80bf-c067091e597d)

**Comment by jlpoltrack** [comment]
Done for E5 and E77
